version: '2'
services:
  sgtservice-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/sgtservice/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sgtservice
      - POSTGRES_PASSWORD=sgtservice
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
